### ISSUE TITLE
非常感谢！这是目前又新又完美的IPQ6000解决方案！

### ISSUE THREAD

**Issue by refined-fish** [Achang233/ZN-M2-OPENWRT-WIFI#3]
——*不知道在此处表达感谢是否不合礼仪，如有冒犯还请见谅，我会即刻删除*

受害于高通不太友好的开源支持，ipq6000的固件实际上非常少：

- openWRT官方源码并不支持此设备
- Lean大佬的版本较为老旧，已经无法与一些插件混合编译
- sdf大佬的版本较新，但很可惜没有WIFI

很高兴能在这里看见二者的结合版本，**插件兼容性很棒！非常感谢！**

**Comment by Zyilin98** [comment]
🤣🤣🤣我也只是找到了 sdf原来的wifi分支，稍微改了一点东西可以正常编译，将来的目标肯定是继续移植sdf佬的分支更新，但是我最近没有时间，可能有时间会接着维护吧。最近在用X86确实是没有动力维护ipq6000了。

**Comment by refined-fish** [comment]
> 🤣🤣🤣我也只是找到了 sdf原来的wifi分支，稍微改了一点东西可以正常编译，将来的目标肯定是继续移植sdf佬的分支更新，但是我最近没有时间，可能有时间会接着维护吧。最近在用X86确实是没有动力维护ipq6000了。

其实主力使用也是x86，不过这个小机器实在是很适合放在一些其他地方再用虚拟链路组网23333，毕竟很便宜性能又强🤣

**Comment by refined-fish** [comment]
> 🤣🤣🤣我也只是找到了 sdf原来的wifi分支，稍微改了一点东西可以正常编译，将来的目标肯定是继续移植sdf佬的分支更新，但是我最近没有时间，可能有时间会接着维护吧。最近在用X86确实是没有动力维护ipq6000了。

好像最近commit更新后，无线又不能使用了🥲

**Comment by Zyilin98** [comment]
> 好像最近commit更新后，无线又不能使用了🥲

更新后没修，有时间我修一下最近在搞5g模组，还没时间。 你试试把feed源换回来之前的再试试可能会能用

**Comment by refined-fish** [comment]
> > 好像最近commit更新后，无线又不能使用了🥲
> 
> 更新后没修，有时间我修一下最近在搞5g模组，还没时间。 你试试把feed源换回来之前的再试试可能会能用

好的嘞🥰

**Comment by refined-fish** [comment]
> > 好像最近commit更新后，无线又不能使用了🥲
> 
> 更新后没修，有时间我修一下最近在搞5g模组，还没时间。 你试试把feed源换回来之前的再试试可能会能用

抱歉再打扰一下，最新的commit仅更换feeds并不生效，不过我离线大佬最后的commit之后能编译出来，但是发现了一个奇怪的问题🥲。
### 问题简述
使用commit 89cba8789f5bf792bab4d3cc9255982ea2e4548c版本编译固件后，无法解析*.scu.qing-yu.top这个域名。
### 详细情况
*.scu.qing-yu.top对应着一个私有地址，使用流量或其他任意网络均可成功解析其地址，但上述编译固件ping返回“bad address”，保持同一路由器硬件，同一接入网络（MAC地址、获取IP、获取DNS服务器均一致）的前提下，更换刷入的其他openWRT固件即可正确解析地址（新固件中本身并不保存该域名的ip，因为这是一个我的私人域名）。
### 复现步骤
使用该commit任意编译固件刷入后直接ping问题域名即可，无需特殊处理，设备为硬改1G内存的ZN_M2路由器。
### 希望得到的帮助
是否openWRT固件有什么部分对DNS有影响？我并不是很精通openWRT，毕竟相同硬件获取相同DNS服务器的情况下这实在太奇怪了，希望能正确解析该地址，我需要它实现本地的服务，另外感觉搞不清楚是一种隐患🤣，不过硬要说属于我的个人需求，如果大佬有时间看看的话最好，没精力就算啦🥰。

**Comment by Zyilin98** [comment]
> > > 好像最近commit更新后，无线又不能使用了🥲
> > 
> > 
> > 更新后没修，有时间我修一下最近在搞5g模组，还没时间。 你试试把feed源换回来之前的再试试可能会能用
> 
> 抱歉再打扰一下，最新的commit仅更换feeds并不生效，不过我离线大佬最后的commit之后能编译出来，但是发现了一个奇怪的问题🥲。
> 
> ### 问题简述
> 使用commit 89cba8789f5bf792bab4d3cc9255982ea2e4548c版本编译固件后，无法解析*.scu.qing-yu.top这个域名。
> 
> ### 详细情况
> *.scu.qing-yu.top对应着一个私有地址，使用流量或其他任意网络均可成功解析其地址，但上述编译固件ping返回“bad address”，保持同一路由器硬件，同一接入网络（MAC地址、获取IP、获取DNS服务器均一致）的前提下，更换刷入的其他openWRT固件即可正确解析地址（新固件中本身并不保存该域名的ip，因为这是一个我的私人域名）。
> 
> ### 复现步骤
> 使用该commit任意编译固件刷入后直接ping问题域名即可，无需特殊处理，设备为硬改1G内存的ZN_M2路由器。
> 
> ### 希望得到的帮助
> 是否openWRT固件有什么部分对DNS有影响？我并不是很精通openWRT，毕竟相同硬件获取相同DNS服务器的情况下这实在太奇怪了，希望能正确解析该地址，我需要它实现本地的服务，另外感觉搞不清楚是一种隐患🤣，不过硬要说属于我的个人需求，如果大佬有时间看看的话最好，没精力就算啦🥰。

我先问一些问题，这个域名是指向你私有的服务对吧 ，这个私有服务在正常解析的时候，解析的结果是内网地址吗？具体这个解析结果是你通过host指定还是在域名解析记录里写了记录

**Comment by refined-fish** [comment]
> > > > 好像最近commit更新后，无线又不能使用了🥲
> > > 
> > > 
> > > 更新后没修，有时间我修一下最近在搞5g模组，还没时间。 你试试把feed源换回来之前的再试试可能会能用
> > 
> > 
> > 抱歉再打扰一下，最新的commit仅更换feeds并不生效，不过我离线大佬最后的commit之后能编译出来，但是发现了一个奇怪的问题🥲。
> > ### 问题简述
> > 使用commit 89cba8789f5bf792bab4d3cc9255982ea2e4548c版本编译固件后，无法解析*.scu.qing-yu.top这个域名。
> > ### 详细情况
> > *.scu.qing-yu.top对应着一个私有地址，使用流量或其他任意网络均可成功解析其地址，但上述编译固件ping返回“bad address”，保持同一路由器硬件，同一接入网络（MAC地址、获取IP、获取DNS服务器均一致）的前提下，更换刷入的其他openWRT固件即可正确解析地址（新固件中本身并不保存该域名的ip，因为这是一个我的私人域名）。
> > ### 复现步骤
> > 使用该commit任意编译固件刷入后直接ping问题域名即可，无需特殊处理，设备为硬改1G内存的ZN_M2路由器。
> > ### 希望得到的帮助
> > 是否openWRT固件有什么部分对DNS有影响？我并不是很精通openWRT，毕竟相同硬件获取相同DNS服务器的情况下这实在太奇怪了，希望能正确解析该地址，我需要它实现本地的服务，另外感觉搞不清楚是一种隐患🤣，不过硬要说属于我的个人需求，如果大佬有时间看看的话最好，没精力就算啦🥰。
> 
> 我先问一些问题，这个域名是指向你私有的服务对吧 ，这个私有服务在正常解析的时候，解析的结果是内网地址吗？具体这个解析结果是你通过host指定还是在域名解析记录里写了记录

正常解析时是私有地址，其来源是我的DDNS服务，通过接口获取内网IP，发送至阿里云DNS，并非本地指定的host等方法

**Comment by Zyilin98** [comment]
嗷大概是形如这种的解析？
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/61766598/7debbbdc-4abc-4bb4-ac69-5eec7b544346)
如果是这种 大概率我知道是哪里的问题了

[use dalao‘s luci&packages](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/commit/89cba8789f5bf792bab4d3cc9255982ea2e4548c) 这个commit，本意是防止sdf大佬删库/删除对wifi支持的库，而自己维护的一个feed源，目前是与sdf的源同步更新，没有做什么修改。

你打开你路由的luci界面 试试像图内一样将这个重绑定保护取消掉，然后再试试
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/61766598/8adf0b2a-a47e-46d7-882d-88933857037b)

**Comment by refined-fish** [comment]
> 嗷大概是形如这种的解析？ ![image](https://user-images.githubusercontent.com/61766598/270362629-7debbbdc-4abc-4bb4-ac69-5eec7b544346.png) 如果是这种 大概率我知道是哪里的问题了
> 
> [use dalao‘s luci&packages](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/commit/89cba8789f5bf792bab4d3cc9255982ea2e4548c) 这个commit，本意是防止sdf大佬删库/删除对wifi支持的库，而自己维护的一个feed源，目前是与sdf的源同步更新，没有做什么修改。
> 
> 你打开你路由的luci界面 试试像图内一样将这个重绑定保护取消掉，然后再试试 ![image](https://user-images.githubusercontent.com/61766598/270363645-8adf0b2a-a47e-46d7-882d-88933857037b.png)

还真是，关了就好了，我其他固件默认没打开这个选项，我之前就是猜测可能有什么类似排出私有地址之类的选项，但是openWRT的设置好多我都看不懂🤣

**Comment by Zyilin98** [comment]
wifi这个问题我尽力修吧，最近被5G模块搞得焦头烂额，最近也就是看了看commit，还没找到wifi究竟是在哪个commit被砍了，不够好像之前hostapd的问题被修复了，接下来就主攻WiFi驱动了

**Comment by refined-fish** [comment]
> wifi这个问题我尽力修吧，最近被5G模块搞得焦头烂额，最近也就是看了看commit，还没找到wifi究竟是在哪个commit被砍了，不够好像之前hostapd的问题被修复了，接下来就主攻WiFi驱动了

其实就目前来说，完全也是能用的，因为高通的原因，内核停留在4.4.60，这种情况下感觉也没有太多的更新的提升（非专业见解）。不过有一位大佬的luci非常好用，我的X86就是他的固件，这个是地址https://github.com/kiddin9/luci/tree/openwrt-23.05-1。目前这个ipq6000应该是openWRT的官方luci，在很多地方有不方便的，kiddin9这位大佬的luci界面非常漂亮，还实现了一些官方没有的功能。不过好像不能直接替换编译，不知道想要换这个应该如何学习🤣

**Comment by Zyilin98** [comment]
这个项目当时sdf佬移植的是immortalwrt的luci，他做了1806分支和2102分支的杂交，保证了luci-app的兼容，你说的这个项目用的是23.05的分支，这个分支官方修改的东西就很多了，不过你说非常漂亮可能是换了一个luci主题，op官方的luci主题一直很丑的......
至于openwrt学习，我还真不知道有啥渠道，不过我记得有相关书籍来着？然后lean以前是一直推荐佐大(佐须之男)的教程系列。你可以关注一下。

**Comment by refined-fish** [comment]
> 这个项目当时sdf佬移植的是immortalwrt的luci，他做了1806分支和2102分支的杂交，保证了luci-app的兼容，你说的这个项目用的是23.05的分支，这个分支官方修改的东西就很多了，不过你说非常漂亮可能是换了一个luci主题，op官方的luci主题一直很丑的...... 至于openwrt学习，我还真不知道有啥渠道，不过我记得有相关书籍来着？然后lean以前是一直推荐佐大(佐须之男)的教程系列。你可以关注一下。

Kiddin9有很多分支，他从比较早期的版本就开始维护他自己的luci了，不是主题，他的固件交互逻辑就已经有一些不一样了，例如他的“主机名”并不是“网络”下的单独子页面，而是合并到了“DHCP/DNS”子页面中，他的“软件包”页面刷新列表/更新软件包按钮是常驻的，而且还能在本页面上传ipk安装，此外在点击安装软件包时会弹出如下界面
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/93998080/392f0ece-c015-4c11-8962-1455b1312015)
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/93998080/c7730c56-5955-41ec-8f07-3d34997a73f2)

**Comment by refined-fish** [comment]
> 这个些修改，如果你用过immortalwrt的21.02-23.05版本就发现，这个功能好像是上游的的修改.......

淦，是我智障了，
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/93998080/46352ff2-3ce9-4f71-a744-dc5d6a2ba6e6)
这个编译出来版本号为啥是这样的，被他欺骗了🤣，我试了下SSH输出是19.07

**Comment by Zyilin98** [comment]
> > 这个些修改，如果你用过immortalwrt的21.02-23.05版本就发现，这个功能好像是上游的的修改.......
> 
> 淦，是我智障了， ![image](https://user-images.githubusercontent.com/93998080/270374532-46352ff2-3ce9-4f71-a744-dc5d6a2ba6e6.png) 这个编译出来版本号为啥是这样的，被他欺骗了🤣，我试了下SSH输出是19.07

编译的时候这个可以修改的，如果你翻过sdf那个分支commit就会发现他也会造这个“假”修改openwrt版本，
~~要不哪天我也造个假版本更到23.09?~~

**Comment by refined-fish** [comment]
> > > 这个些修改，如果你用过immortalwrt的21.02-23.05版本就发现，这个功能好像是上游的的修改.......
> > 
> > 
> > 淦，是我智障了， ![image](https://user-images.githubusercontent.com/93998080/270374532-46352ff2-3ce9-4f71-a744-dc5d6a2ba6e6.png) 这个编译出来版本号为啥是这样的，被他欺骗了🤣，我试了下SSH输出是19.07
> 
> 编译的时候这个可以修改的，如果你翻过sdf那个分支commit就会发现他也会造这个“假”修改openwrt版本， ~要不哪天我也造个假版本更到23.09?~

哈哈哈哈哈🤣，我搜到修改的教程了，我之前还天真的以为真的版本变了，导致我认为luci的提升与版本无关

**Comment by Zyilin98** [comment]
问一下 你最近编译有遇到hostapd 这个包编译出错的情况吗 如果没有 可以告诉我你可以编译出包的最后的commit是哪一个？最近在解决这个奇怪的问题，感觉是wifi驱动导致的问题，但是我找不到具体是那个commit导致的问题

**Comment by refined-fish** [comment]
这是编译选择情况，没有选择hostapd，带common的选择了。我不是很了解这个方面，似乎默认就没有选中hostapd？上图的配置是不会出错的
&nbsp;


超高校级の錆鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amatsume ***@***.***&gt;; 
发送时间: 2023年10月3日(星期二) 下午3:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Achang233/ZN-M2-OPENWRT-WIFI] 非常感谢！这是目前又新又完美的IPQ6000解决方案！ (Issue #3)





 
问一下 你最近编译有遇到hostapd 这个包编译出错的情况吗 如果没有 可以告诉我你可以编译出包的最后的commit是哪一个？最近在解决这个奇怪的问题，感觉是wifi驱动导致的问题，但是我找不到具体是那个commit导致的问题

**Comment by refined-fish** [comment]
> 问一下 你最近编译有遇到hostapd 这个包编译出错的情况吗 如果没有 可以告诉我你可以编译出包的最后的commit是哪一个？最近在解决这个奇怪的问题，感觉是wifi驱动导致的问题，但是我找不到具体是那个commit导致的问题

才发现图没发出来，这个邮箱回复好鸡肋，commit还是上一个能用的89cba8789f5bf792bab4d3cc9255982ea2e4548c，选择如下图
![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/93998080/4045cd67-88dc-4009-ab4c-ae16ddf6f817)

**Comment by Zyilin98** [comment]
下面的wpa-openssl没有选对吧，谢谢帮助

**Comment by refined-fish** [comment]
> 下面的wpa-openssl没有选对吧，谢谢帮助

![image](https://github.com/Achang233/ZN-M2-OPENWRT-WIFI/assets/93998080/8fcde586-8588-47fb-8434-c0994b44d4e0)
选了的耶

**Comment by Zyilin98** [comment]
好
